language: cpp
dist: xenial

matrix:
  include:
#    - name: "osx gcc-7"
#      os: osx
#      osx_image: xcode10
#      env: MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Release

#    - name: "osx gcc-8"
#      os: osx
#      osx_image: xcode10
#      env: MATRIX_EVAL="brew install gcc@8 && CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release

    - name: "linux gcc-8"
      os: linux
      addons:
        apt: { packages: [g++-8],
               sources:  [ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release

    - name: "linux gcc-9"
      os: linux
      addons:
        apt: { packages: [g++-9],
               sources:  [ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" BUILD_TYPE=Release

    - name: "linux gcc-9 (coverage)"
      os: linux
      addons:
        apt: { packages: [g++-9, lcov],
               sources:  [ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" BUILD_TYPE=Coverage GCOV=gcov-9

    - name: "linux clang-7"
      os: linux
      addons:
        apt: { packages: [clang-7, g++-7],
               sources:  [llvm-toolchain-xenial-7, ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Release

    - name: "linux clang-8"
      os: linux
      addons:
        apt: { packages: [clang-8, g++-8],
               sources:  [llvm-toolchain-xenial-8, ubuntu-toolchain-r-test] }
      env: MATRIX_EVAL="CC=clang-8 && CXX=clang++-8" BUILD_TYPE=Release

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVERBOSE_CONFIG=ON -DGANON_OFFSET=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - cat compile_commands.json
  - cmake --build . -- -j2
  - ctest -VV .

after_success:
  - if [ "$BUILD_TYPE" == "Coverage" ]; then 
      lcov --gcov-tool $(which ${GCOV}) -d . -c -o coverage.info;
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports";
    fi

notifications:
  email: false
