language: cpp

matrix:
  include:
    - name: "g++-7"
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: COMP_CPP=g++-7

script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMP_CPP ..
  - cmake --build .
