language: cpp

matrix:
  include:
    - name: "linux gcc-7"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: "linux clang-6"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-7 # for libstdc++ dependency
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DVERBOSE_CONFIG=ON ..
  - cmake --build .
  - ./ganon-build
  - ./ganon-classify
  - ./ganon-update

notifications:
  email: false
